# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  t4_config = debug
endif
ifeq ($(config),release)
  t4_config = release
endif

PROJECTS := t4

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

t4:
ifneq (,$(t4_config))
	@echo "==== Building t4 ($(t4_config)) ===="
	@${MAKE} --no-print-directory -C . -f t4.make config=$(t4_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f t4.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   t4"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"